name: Deploy Java App to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform
      
      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_private_key_path: ${{ secrets.PRIVATE_KEY_PATH }}
