name: Terraform CI CD Pipeline for Deploying AWS Resources
run-name: ${{ github.actor }} has triggered the pipeline

on:
  push:
    branches:
      - main
      
env :
      TF_VAR_aws_access_key_id : ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_access_key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_session_token : ${{ secrets.AWS_SESSION_TOKEN }}
      TF_VAR_private_key_path : ${{ secrets.PRIVATE_KEY_PATH }}
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
          aws configure set region ${{ secrets.AWS_REGION }}
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: terraform init
      - name : Plan Terraform
        run : terraform plan
      - name: Apply Terraform
        run: terraform apply -auto-approve
        